controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_controller:
  ros__parameters:
    joints:
      - base_link_revolucion-5
      - arm1_revolucion-6
      - arm2_revolucion-7
      - arm3_revolucion-8
      - arm4_revolucion-9
      - arm5_revolucion-11
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
